# Generated by Django 5.0.4 on 2024-05-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlog',
            name='name',
            field=models.CharField(max_length=225, verbose_name='название статьи'),
        ),
        migrations.AlterField(
            model_name='vlog',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='vlog/', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='vlog',
            name='slug',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='slug'),
        ),
    ]
