# Generated by Django 5.0.4 on 2024-04-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='photo',
            new_name='preview',
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Описание'),
        ),
    ]
